### ISSUE TITLE
Ecto Explain error installing

### ISSUE THREAD

**Issue by phanhuyanh** [revelrylabs/ecto_explain#7]
I followed instruction install ecto_explain. But I got message ``` def explain/3 defaults conflicts with explain/2```

**Comment by phanhuyanh** [comment]
@brianberlin Help me!

**Comment by brianberlin** [comment]
i'm sorry this is an old package that needs to be removed or read me updated. since this package was published ecto has made an explain function available. link below

https://hexdocs.pm/ecto_sql/Ecto.Adapters.SQL.html#explain/4

**Comment by phanhuyanh** [comment]
@brianberlin thank you!
